# GitHub Sponsors configuration (optional)
# Uncomment and add your info if you want to enable sponsorship

# github: YOUR_GITHUB_USERNAME
# patreon: YOUR_PATREON_USERNAME
# custom: ["https://your-website.com/donate"]
